exports.QUERY_NOVEL_FIND_ALL = 'ALL';
exports.QUERY_NOVEL_FIND_ACTION = 'ACTION';
exports.QUERY_NOVEL_FIND_COMEDY = 'COMEDY';
exports.QUERY_NOVEL_FIND_DRAMA = 'DRAMA';
exports.QUERY_NOVEL_FIND_FANTASY = 'FANTASY';
exports.QUERY_NOVEL_FIND_ROMANCE = 'ROMANCE';
exports.QUERY_NOVEL_FIND_THRILLER = 'THRILLER';
